config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles
  devise_for :users

  root "articles#index"

  get 'about', to: 'welcome#about'
  get 'news', to: 'articles#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    can :read, Article
    cannot :read, Article, published_at: nil

    return unless user.present?

    can :create, Article
    can :read, Article, author_id: user.id
    can :edit, Article, author_id: user.id, published_at: nil
    can :destroy, Article, author_id: user.id, published_at: nil
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :category

  has_rich_text    :body

  has_one_attached :preview_img

  validates :body, presence: true
  validates :title, presence: true
  validates :preview_img, presence: true

  friendly_id :title, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/categories/sorted_collection.rb
module Categories::SortedCollection
  def categories_list
    Category.where.not(key: 'inshe') + Category.where(key: 'inshe')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend Categories::SortedCollection

  before_create :set_key
  has_many :articles

  private

  def set_key
    self.key = I18n.transliterate(self.title).parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_categories, only: %i[ new create edit update ]

  def index
    @articles = Article.accessible_by(current_ability)

    if category = Category.find_by(key: params[:category_key])
      @articles = @articles.where(category: category)
    end
  end

  def show
    authorize! :read, @article
  end

  def new
    @article = Article.new
    authorize! :create, @article
  end

  def edit
    authorize! :edit, @article
  end

  def create
    @article = current_user.articles.build(article_params)
    authorize! :create, @article

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :edit, @article

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @article

    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :preview_img, :category_id)
  end

  def set_categories
    @categories_array = Category.categories_list.pluck(:title, :id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/header_helper.rb
module HeaderHelper
  def current_link_class(path)
    current_page?(path) ? 'nav-link px-2 link-secondary' : 'nav-link px-2 link-dark'
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <h1 class='text-center'><%= article.title %></h1>
  <p>
    <%= article.body %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, t('articles.form.labels.title'), style: 'display: block' %>
    <%= form.text_field :title, class: 'w-100' %>
  </div>
  <div>
    <%= form.label :preview_image, t('articles.form.labels.preview_img'), style: 'display: block' %>
    <%= form.file_field :preview_img %>
  </div>
  <div>
    <%= form.label :body, t('articles.form.labels.body'), style: 'display: block' %>
    <%= form.rich_text_area :body %>
  </div><br>

  <div>
    <%= form.label :category_id, t('articles.form.labels.category'), style: 'display: block' %>
    <%= form.select :category_id, @categories_array, prompt: t('articles.form.labels.choose') %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_index_article.html.erb
<div class="col" id="<%= dom_id article %>">
  <div class="card shadow-sm">
    <%- if article.preview_img.present? %>
      <%= image_tag article.preview_img %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    <% end %>

    <div class="card-body">
      <p class="card-text"><%= article.title %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to article do %>
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= t('buttons.show') %></button>
          <% end %>
          <% if can? :edit, article %>
            <%= link_to edit_article_path(article) do %>
              <button type="button" class="btn btn-sm btn-outline-secondary"><%= t('buttons.edit') %></button>
            <% end %>
          <% end %>
        </div>
        <%#<small class="text-muted">9 mins</small>%>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1><%= t('articles.buttons.edit') %></h1>

<div class='col-10 offset-1'>
  <%= render "form", article: @article %>
</div>

<br>

<div>
  <%= link_to t('buttons.show'), @article %> |
  <%= link_to t('buttons.all_articles'), articles_path %>
</div>

app/views/articles/index.html.erb
<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id='articles'>
        <% @articles.each do |article| %>
          <%= render 'index_article', article: article %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/articles/new.html.erb
<h1><%= t('articles.buttons.new') %></h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<div class='row'>
  <div class="col-6">
    <%= link_to t('buttons.all_articles'), articles_path %>
  </div>
  <div class="col-6 text-right">
    <% if can? :edit, @article %>
      <%= link_to t('buttons.edit'), edit_article_path(@article), class: 'd-inline inline-right btn btn-secondary' %>
    <% end %>
    <% if can? :destroy, @article %>
      <%= button_to t('buttons.delete'), @article, method: :delete, form_class: 'd-inline inline-right', class: ' btn btn-secondary mr-5' %>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col-10 offset-1'>
    <%= render @article %>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<p class="notice" style="color: green"><%= notice %></p>
<p class="alert" style="color: red"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%= link_to t('buttons.up'), '#' %>
    </p>
    <p class="mb-1">© <%= Date.today.year %> KavaFans. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to root_path do %>
        <%= image_tag('logo.svg', width: '250px') %>
      <% end %>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <%= link_to t('header.menu.news'), news_path, class: current_link_class(news_path) %>
        </li>

        <% Category.categories_list.each do | category |%>
          <li>
            <%= link_to category.title, articles_path(category_key: category.key), class: current_link_class(articles_path(category_key: category.key)) %>
          </li>
        <% end %>
        <li>
          <%= link_to t('header.menu.about'), about_path, class: current_link_class(about_path) %>
        </li>
      </ul>

      <%- if user_signed_in? %>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><%= link_to t('articles.buttons.new'), new_article_path, class: 'dropdown-item' %></li>
            <li><%= link_to t('devise.account'), edit_user_registration_path, class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= button_to t('devise.logout'), destroy_user_session_path, method: :delete, form: {turbolink: false}, class: 'dropdown-item' %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class='text-end'>
          <%= link_to new_user_session_path do %>
            <button type='button' class='btn btn-primary me-2'><%= t('devise.sessions.new.sign_in') %></button>
          <% end %>
          <%= link_to new_user_registration_path do %>
            <button type='button' class='btn btn-warning'><%= t('devise.registrations.new.sign_up') %></button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KavaFans</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("application") %>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_message' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light"><%= t('welcome.title') %></h1>
      <p class="lead text-muted"><%= t('welcome.description') %></p>
    </div>
  </div>

  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h2 class="fw-light">Чек ліст запланованого функіоналу:</h2>
      <ul>
        <li>Теги</li>
        <li>Фільтри по категоріям</li>
        <li>Додаткові поля про автора</li>
        <li>Лайки</li>
        <li>Коментарі</li>
        <li>Пошук по тектсу</li>
        <li>Пошук по автору</li>
        <li>Гарна сітка переліку статей</li>
      </ul>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>